### ISSUE TITLE
Requirements-checker verbose mode?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/requirements-checker#13]
This issue was originally created by @garak in https://github.com/symfony/symfony/issues/24271

-----

| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Symfony version  | any

I need to communicate to an hosting provider the requirements for a Symfony application.
Unfortunately, it looks like there's no way to get such list from requirements-checker, unless you run it on a place where no requirement is met.
It would be nice if we could activate a verbose mode, where requirements-checker is not just displaying green dots, but instead is displaying full informations, so we can copy/paste them.
Of course, the same can apply to check.php web output.

**Comment by fabpot** [comment]
Looks like a good idea to me. I think doing the verbose mode on the CLI only is good enough. Anyone willing to work on that?

**Comment by javiereguiluz** [comment]
I'd like to work on this feature!
