### ISSUE TITLE
Ask for check.php file deletion after removing the module

### ISSUE THREAD

**Issue by lopezator** [symfony/requirements-checker#16]
After the package removal the check.php is useless, so it would be nice to delete it automatically or at least recommend/ask for permission/print a message.

**Comment by fabpot** [comment]
That's already the case if you are using Flex. Or are you saying it does not work for you?

**Comment by lopezator** [comment]
Dindn't worked for me.

**Comment by fabpot** [comment]
Then, there is a bug somewhere. Can you try to debug that? And report the issue on symfony/flex? Thank you.
