### ISSUE TITLE
Configured default timezone "Asia/Dubai" must be supported by your installation of PHP

### ISSUE THREAD

**Issue by majidmvulle** [symfony/requirements-checker#17]
But "Asia/Dubai" is listed on the PHP timezones.

http://php.net/manual/en/timezones.asia.php

**Comment by fabpot** [comment]
Not sure what this issue means. Without more information, there is nothing we can do. In any case, you should probably ask for support on StackOverflow.

**Comment by majidmvulle** [comment]
Thanks @fabpot, I will check on StackOverflow. It's related to setting `Asia/Dubai` as the default timezone in php.ini, but the requirements-checker throws the error: `Configured default timezone "Asia/Dubai" must be supported by your installation of PHP`.
