### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rfarzaliev** [symfony/requirements-checker#20]
php 7.2.4
composer 1.6.4
sf 4.0

$ composer require symfony/requirements-checker
Using version ^1.0 for symfony/requirements-checker
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/requirements-checker (v1.0.4): Downloading (connecting...
Downloading (100%)
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Symfony operations: 1 recipe (8656faab286fc36f7c0c086d5a9f4d88)
  - Configuring symfony/requirements-checker (>=1.0): From github.com/symfony/recipes:master
Executing script cache:clear [OK]
Executing script assets:install --symlink --relative public [OK]
Executing script requirements-checker [KO]
 [KO]
Script requirements-checker returned with error code 255
!!
!!  Fatal error: Uncaught Error: Class 'Symfony\Requirements\InvalidArgumentException' not found in C:\Users\...\vendor\symfony\requirements-checker\src\PhpConfigRequirement.php:41
!!  Stack trace: ...

**Comment by fabpot** [comment]
fixed in 32b9f96
