### ISSUE TITLE
Do a better comparison of ini_get() integers values

### ISSUE THREAD

**Issue by clem** [symfony/requirements-checker#23]
When comparing `memory_limit`, `post_max_size` and `upload_max_size`, it's not a real comparison that is made. It could be great if comparison handle real numbers conversion.

For example, if `memory_limit` is set to `2G`, it's it greater than a post_max_size set to `8M`, but it's not really the case now.

The allowed formats are `K`, `M` and `G` (cf: [Using shorthand bytes](http://www.php.net/manual/en/faq.using.php#faq.using.shorthandbytes))

**Comment by garak** [comment]
What about unlimited memory? I just tried with a system with memory_limit -1, it's considered less than post_max_size

**Comment by clem** [comment]
@garak Thanks for your feedback! I just pushed a fix for the unlimited alias 😊
