### ISSUE TITLE
feature request: quiet mode

### ISSUE THREAD

**Issue by famoser** [symfony/requirements-checker#32]
I run `bin/requirements-checker` after composer install together with some other checks like security, cghooks, migrations, ... 

Unfortunately, even without the `-v` option, the output contains to me irrelevant details like which `php.ini` is used or the note that the `php.ini` file used by the webserver could be different. This pollutes the command line, and its easier to miss other more relevant output of the other commands.

I am only interested in a hard fail/pass to ensure my environment is ready & optimized to develop symfony applications.

Hence I would propose a new `-q` flag which prevents the output of the informational text like where the php.ini is located or that the command line could use a different config file. If errors and warnings are found, these are however still printed in the same way it would be done without the `-q` flag.

If this sounds good, I will create a PR in the next days.

**Comment by Tobion** [comment]
We could also print the additional, informative text to stderr. This way you could just ignore the stderr output if u want.

**Comment by famoser** [comment]
And the `-q` flag would then disable if the stderr output is redirected to `stdout` (which would need to be the default)?

This seems strange to me; this would mean we write the informative messages to `stderr` and the real errors to `stdout`. Or is there a benefit I am missing? I am not used to console programs.
