### ISSUE TITLE
Version check is not correct when multiple versions of PHP on Ubuntu

### ISSUE THREAD

**Issue by ChristopheFerreboeuf** [symfony/requirements-checker#36]
Step to reproduce : 
- Have a Ubuntu where many versions of PHP are installed (5.6, 7.1, 7.2, 7.3 in my case)
- Switch to PHP7.3 if not yet active
- Launch `symfony check:requirements`
Result is : 
![Screenshot_20190902_095000](https://user-images.githubusercontent.com/10241898/64095716-4a65f700-cd68-11e9-934c-a08416a74893.png)

Result should be like : 

```
php -i | grep "Configuration File"
Configuration File (php.ini) Path => /etc/php/7.3/cli
Loaded Configuration File => /etc/php/7.3/cli/php.ini
```

**Comment by fabpot** [comment]
What does "Switch to PHP7.3 if not yet active" means here? Is it active because you created a `.php-version` file or because it's the on in `$PATH`? Or something else?

**Comment by ChristopheFerreboeuf** [comment]
Thanks for the interest in my issue.

I use a script to switch between different version : https://gist.github.com/ChristopheFerreboeuf/68e93913c6808729867dcdd7d9cb501d

I also tried to do it in that way : https://www.ostechnix.com/how-to-switch-between-multiple-php-versions-in-ubuntu/

I have multiple versions for different projects and I need to switch between them so I have different versions of PHP. The oldest is PHP5.6.

**Comment by fabpot** [comment]
Having several PHP versions is not a problem and it is supported. What is the output of `symfony local:php:list`?

**Comment by ChristopheFerreboeuf** [comment]
The result is : 

![image](https://user-images.githubusercontent.com/10241898/64230130-99d92e00-cef4-11e9-811d-1ad7e110a10d.png)

I think it is linked with my installation of Ubuntu as it is a 18.04 but was upgraded from 14.04 then 16.04. I will invistigate how to change that because /usr/bin/php links to php7.3. 

Thanks for the help.
