### ISSUE TITLE
Allow SymfonyRequirements' helper methods to be used in child class

### ISSUE THREAD

**Issue by gnutix** [symfony/requirements-checker#37]
I'm writing a custom Requirements class for a CMS that extends `SymfonyRequirements` (which is not `final`). However, some helper methods in there would be useful to me (`convertShorthandSize` and php-config-related methods) but these are `private`.

Would you rather turn them to `protected` or extract them in a separate `trait` (that could be used in both classes) ?

Let me know and I'll implement it.

**Comment by Tobion** [comment]
traits are only available since php 5.4 and the requirements checker is currently compatible with php 5.3. `convertShorthandSize` seems pretty simple. can't you copy it simply?

**Comment by gnutix** [comment]
I did, in the end. Good point about traits. What about protected ? (as the class isn't final)
