### ISSUE TITLE
ProjectRequirements Symfony version detection broken

### ISSUE THREAD

**Issue by lazka** [symfony/requirements-checker#49]
ProjectRequirements gets called with the path to "composer.json", but the code in there expects the root directory, so it fails and defaults to the newest PHP version. https://github.com/symfony/requirements-checker/blob/e158a5ba12e1b84e2086a9a34ff9b63b03c5c1ed/bin/requirements-checker.php#L43C1-L43C113

This results in composer install failing with Symfony 6.4 and requesting PHP 8.2 to be installed if 8.1 is installed.

This was exposed by c195b8aa187d46dc943cc91e5bad7c1c20941c68 which now makes the error case default to the newest PHP version instead of the oldest.

Using Symfony 6.4 with PHP 8.1:

```
Script requirements-checker returned with error code 1
!!  
!!  Symfony Requirements Checker
!!  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!  
!!  > PHP is using the following php.ini file:
!!  /etc/php/8.1/cli/php.ini
!!  
!!  > Checking Symfony requirements:
!!  
!!  ...........E.............W...........
!!  
!!                                                    
!!   [ERROR]                                          
!!   Your system is not ready to run Symfony projects 
!!                                                    
!!  
!!  Fix the following mandatory requirements
!!  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!  
!!   * PHP version must be at least 8.2.0 (8.1.28 installed)
!!     > Install PHP 8.2.0 or newer (installed version is 8.1.28)
```

I would suggest to default to the oldest PHP version again, in case extracting the Symfony version fails.

**Comment by fnagel** [comment]
Same issue here, downgrading to 2.0.1 helps.
